if (APPLE)
    message(FATAL_ERROR "macOS 不支持DirectML")
elseif (WIN32)
    if (CMAKE_CL_64)
        message("配置WINDOWS OnnxRuntime_DirectML x64 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x64")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x64")
    else ()
        message("配置WINDOWS OnnxRuntime_DirectML x86 路径: ${CMAKE_CURRENT_LIST_DIR}/windows-x86")
        set(OnnxRuntime_DIR "${CMAKE_CURRENT_LIST_DIR}/windows-x86")
    endif ()
elseif (UNIX)
    message(FATAL_ERROR "Linux 不支持DirectML")
endif ()

